/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.cassandra;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface InterNode {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"InterNode\",\"namespace\":\"org.apache.cassandra\",\"types\":[{\"type\":\"fixed\",\"name\":\"UUID\",\"namespace\":\"org.apache.cassandra.utils.avro\",\"size\":16},{\"type\":\"record\",\"name\":\"AddColumnFamily\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"cf\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"AddKeyspace\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"ks\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"DropColumnFamily\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"ksname\",\"type\":\"string\"},{\"name\":\"cfname\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"DropKeyspace\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"ksname\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"RenameColumnFamily\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"ksname\",\"type\":\"string\"},{\"name\":\"cfid\",\"type\":\"int\"},{\"name\":\"old_cfname\",\"type\":\"string\"},{\"name\":\"new_cfname\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"RenameKeyspace\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"old_ksname\",\"type\":\"string\"},{\"name\":\"new_ksname\",\"type\":\"string\"}]}],\"messages\":{\"myRename\":{\"request\":[{\"name\":\"rc\",\"type\":\"string\"}],\"response\":\"int\"}}}");
  int myRename(java.lang.CharSequence rc) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends InterNode {
    public static final org.apache.avro.Protocol PROTOCOL = org.apache.cassandra.InterNode.PROTOCOL;
    void myRename(java.lang.CharSequence rc, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}