// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.example.protocolbuf;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string favorite_number = 2;
    /**
     * <code>optional string favorite_number = 2;</code>
     */
    boolean hasFavoriteNumber();
    /**
     * <code>optional string favorite_number = 2;</code>
     */
    java.lang.String getFavoriteNumber();
    /**
     * <code>optional string favorite_number = 2;</code>
     */
    com.google.protobuf.ByteString
        getFavoriteNumberBytes();

    // optional string favorite_color = 3;
    /**
     * <code>optional string favorite_color = 3;</code>
     */
    boolean hasFavoriteColor();
    /**
     * <code>optional string favorite_color = 3;</code>
     */
    java.lang.String getFavoriteColor();
    /**
     * <code>optional string favorite_color = 3;</code>
     */
    com.google.protobuf.ByteString
        getFavoriteColorBytes();

    // optional string age = 4;
    /**
     * <code>optional string age = 4;</code>
     */
    boolean hasAge();
    /**
     * <code>optional string age = 4;</code>
     */
    java.lang.String getAge();
    /**
     * <code>optional string age = 4;</code>
     */
    com.google.protobuf.ByteString
        getAgeBytes();

    // optional string class1 = 5;
    /**
     * <code>optional string class1 = 5;</code>
     */
    boolean hasClass1();
    /**
     * <code>optional string class1 = 5;</code>
     */
    java.lang.String getClass1();
    /**
     * <code>optional string class1 = 5;</code>
     */
    com.google.protobuf.ByteString
        getClass1Bytes();

    // optional string number = 6;
    /**
     * <code>optional string number = 6;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional string number = 6;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 6;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    // optional string address = 7;
    /**
     * <code>optional string address = 7;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 7;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 7;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    // optional string phone = 8;
    /**
     * <code>optional string phone = 8;</code>
     */
    boolean hasPhone();
    /**
     * <code>optional string phone = 8;</code>
     */
    java.lang.String getPhone();
    /**
     * <code>optional string phone = 8;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes();

    // optional string first_name = 9;
    /**
     * <code>optional string first_name = 9;</code>
     */
    boolean hasFirstName();
    /**
     * <code>optional string first_name = 9;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>optional string first_name = 9;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    // optional string last_name = 10;
    /**
     * <code>optional string last_name = 10;</code>
     */
    boolean hasLastName();
    /**
     * <code>optional string last_name = 10;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>optional string last_name = 10;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();
  }
  /**
   * Protobuf type {@code tutorial.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              favoriteNumber_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              favoriteColor_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              age_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              class1_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              number_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              address_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              phone_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              firstName_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              lastName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protocolbuf.User.internal_static_tutorial_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protocolbuf.User.internal_static_tutorial_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protocolbuf.User.Person.class, com.example.protocolbuf.User.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string favorite_number = 2;
    public static final int FAVORITE_NUMBER_FIELD_NUMBER = 2;
    private java.lang.Object favoriteNumber_;
    /**
     * <code>optional string favorite_number = 2;</code>
     */
    public boolean hasFavoriteNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string favorite_number = 2;</code>
     */
    public java.lang.String getFavoriteNumber() {
      java.lang.Object ref = favoriteNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          favoriteNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string favorite_number = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFavoriteNumberBytes() {
      java.lang.Object ref = favoriteNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        favoriteNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string favorite_color = 3;
    public static final int FAVORITE_COLOR_FIELD_NUMBER = 3;
    private java.lang.Object favoriteColor_;
    /**
     * <code>optional string favorite_color = 3;</code>
     */
    public boolean hasFavoriteColor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string favorite_color = 3;</code>
     */
    public java.lang.String getFavoriteColor() {
      java.lang.Object ref = favoriteColor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          favoriteColor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string favorite_color = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFavoriteColorBytes() {
      java.lang.Object ref = favoriteColor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        favoriteColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string age = 4;
    public static final int AGE_FIELD_NUMBER = 4;
    private java.lang.Object age_;
    /**
     * <code>optional string age = 4;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string age = 4;</code>
     */
    public java.lang.String getAge() {
      java.lang.Object ref = age_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          age_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string age = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAgeBytes() {
      java.lang.Object ref = age_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        age_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string class1 = 5;
    public static final int CLASS1_FIELD_NUMBER = 5;
    private java.lang.Object class1_;
    /**
     * <code>optional string class1 = 5;</code>
     */
    public boolean hasClass1() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string class1 = 5;</code>
     */
    public java.lang.String getClass1() {
      java.lang.Object ref = class1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          class1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string class1 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getClass1Bytes() {
      java.lang.Object ref = class1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        class1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string number = 6;
    public static final int NUMBER_FIELD_NUMBER = 6;
    private java.lang.Object number_;
    /**
     * <code>optional string number = 6;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string number = 6;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          number_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string number = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string address = 7;
    public static final int ADDRESS_FIELD_NUMBER = 7;
    private java.lang.Object address_;
    /**
     * <code>optional string address = 7;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string address = 7;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string phone = 8;
    public static final int PHONE_FIELD_NUMBER = 8;
    private java.lang.Object phone_;
    /**
     * <code>optional string phone = 8;</code>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string phone = 8;</code>
     */
    public java.lang.String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phone_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string phone = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string first_name = 9;
    public static final int FIRST_NAME_FIELD_NUMBER = 9;
    private java.lang.Object firstName_;
    /**
     * <code>optional string first_name = 9;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string first_name = 9;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string first_name = 9;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string last_name = 10;
    public static final int LAST_NAME_FIELD_NUMBER = 10;
    private java.lang.Object lastName_;
    /**
     * <code>optional string last_name = 10;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string last_name = 10;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string last_name = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
      favoriteNumber_ = "";
      favoriteColor_ = "";
      age_ = "";
      class1_ = "";
      number_ = "";
      address_ = "";
      phone_ = "";
      firstName_ = "";
      lastName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFavoriteNumberBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFavoriteColorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAgeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getClass1Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getNumberBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getAddressBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getLastNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFavoriteNumberBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFavoriteColorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAgeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getClass1Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getNumberBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getAddressBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getLastNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.protocolbuf.User.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protocolbuf.User.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protocolbuf.User.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protocolbuf.User.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protocolbuf.User.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.protocolbuf.User.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.protocolbuf.User.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.protocolbuf.User.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.protocolbuf.User.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.protocolbuf.User.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.protocolbuf.User.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.protocolbuf.User.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protocolbuf.User.internal_static_tutorial_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protocolbuf.User.internal_static_tutorial_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protocolbuf.User.Person.class, com.example.protocolbuf.User.Person.Builder.class);
      }

      // Construct using com.example.protocolbuf.User.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        favoriteNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        favoriteColor_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        class1_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protocolbuf.User.internal_static_tutorial_Person_descriptor;
      }

      public com.example.protocolbuf.User.Person getDefaultInstanceForType() {
        return com.example.protocolbuf.User.Person.getDefaultInstance();
      }

      public com.example.protocolbuf.User.Person build() {
        com.example.protocolbuf.User.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.protocolbuf.User.Person buildPartial() {
        com.example.protocolbuf.User.Person result = new com.example.protocolbuf.User.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.favoriteNumber_ = favoriteNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.favoriteColor_ = favoriteColor_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.class1_ = class1_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.phone_ = phone_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.lastName_ = lastName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protocolbuf.User.Person) {
          return mergeFrom((com.example.protocolbuf.User.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protocolbuf.User.Person other) {
        if (other == com.example.protocolbuf.User.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasFavoriteNumber()) {
          bitField0_ |= 0x00000002;
          favoriteNumber_ = other.favoriteNumber_;
          onChanged();
        }
        if (other.hasFavoriteColor()) {
          bitField0_ |= 0x00000004;
          favoriteColor_ = other.favoriteColor_;
          onChanged();
        }
        if (other.hasAge()) {
          bitField0_ |= 0x00000008;
          age_ = other.age_;
          onChanged();
        }
        if (other.hasClass1()) {
          bitField0_ |= 0x00000010;
          class1_ = other.class1_;
          onChanged();
        }
        if (other.hasNumber()) {
          bitField0_ |= 0x00000020;
          number_ = other.number_;
          onChanged();
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000040;
          address_ = other.address_;
          onChanged();
        }
        if (other.hasPhone()) {
          bitField0_ |= 0x00000080;
          phone_ = other.phone_;
          onChanged();
        }
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000100;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000200;
          lastName_ = other.lastName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.protocolbuf.User.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.protocolbuf.User.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string favorite_number = 2;
      private java.lang.Object favoriteNumber_ = "";
      /**
       * <code>optional string favorite_number = 2;</code>
       */
      public boolean hasFavoriteNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string favorite_number = 2;</code>
       */
      public java.lang.String getFavoriteNumber() {
        java.lang.Object ref = favoriteNumber_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          favoriteNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string favorite_number = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFavoriteNumberBytes() {
        java.lang.Object ref = favoriteNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          favoriteNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string favorite_number = 2;</code>
       */
      public Builder setFavoriteNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        favoriteNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string favorite_number = 2;</code>
       */
      public Builder clearFavoriteNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        favoriteNumber_ = getDefaultInstance().getFavoriteNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string favorite_number = 2;</code>
       */
      public Builder setFavoriteNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        favoriteNumber_ = value;
        onChanged();
        return this;
      }

      // optional string favorite_color = 3;
      private java.lang.Object favoriteColor_ = "";
      /**
       * <code>optional string favorite_color = 3;</code>
       */
      public boolean hasFavoriteColor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string favorite_color = 3;</code>
       */
      public java.lang.String getFavoriteColor() {
        java.lang.Object ref = favoriteColor_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          favoriteColor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string favorite_color = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFavoriteColorBytes() {
        java.lang.Object ref = favoriteColor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          favoriteColor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string favorite_color = 3;</code>
       */
      public Builder setFavoriteColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        favoriteColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string favorite_color = 3;</code>
       */
      public Builder clearFavoriteColor() {
        bitField0_ = (bitField0_ & ~0x00000004);
        favoriteColor_ = getDefaultInstance().getFavoriteColor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string favorite_color = 3;</code>
       */
      public Builder setFavoriteColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        favoriteColor_ = value;
        onChanged();
        return this;
      }

      // optional string age = 4;
      private java.lang.Object age_ = "";
      /**
       * <code>optional string age = 4;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string age = 4;</code>
       */
      public java.lang.String getAge() {
        java.lang.Object ref = age_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          age_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string age = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAgeBytes() {
        java.lang.Object ref = age_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          age_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string age = 4;</code>
       */
      public Builder setAge(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string age = 4;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000008);
        age_ = getDefaultInstance().getAge();
        onChanged();
        return this;
      }
      /**
       * <code>optional string age = 4;</code>
       */
      public Builder setAgeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        age_ = value;
        onChanged();
        return this;
      }

      // optional string class1 = 5;
      private java.lang.Object class1_ = "";
      /**
       * <code>optional string class1 = 5;</code>
       */
      public boolean hasClass1() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string class1 = 5;</code>
       */
      public java.lang.String getClass1() {
        java.lang.Object ref = class1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          class1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string class1 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getClass1Bytes() {
        java.lang.Object ref = class1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          class1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string class1 = 5;</code>
       */
      public Builder setClass1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        class1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string class1 = 5;</code>
       */
      public Builder clearClass1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        class1_ = getDefaultInstance().getClass1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string class1 = 5;</code>
       */
      public Builder setClass1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        class1_ = value;
        onChanged();
        return this;
      }

      // optional string number = 6;
      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 6;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string number = 6;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 6;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 6;</code>
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000020);
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 6;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        number_ = value;
        onChanged();
        return this;
      }

      // optional string address = 7;
      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 7;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string address = 7;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 7;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 7;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000040);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 7;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        address_ = value;
        onChanged();
        return this;
      }

      // optional string phone = 8;
      private java.lang.Object phone_ = "";
      /**
       * <code>optional string phone = 8;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string phone = 8;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone = 8;</code>
       */
      public Builder setPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 8;</code>
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000080);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone = 8;</code>
       */
      public Builder setPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        phone_ = value;
        onChanged();
        return this;
      }

      // optional string first_name = 9;
      private java.lang.Object firstName_ = "";
      /**
       * <code>optional string first_name = 9;</code>
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string first_name = 9;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string first_name = 9;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string first_name = 9;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 9;</code>
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000100);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 9;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        firstName_ = value;
        onChanged();
        return this;
      }

      // optional string last_name = 10;
      private java.lang.Object lastName_ = "";
      /**
       * <code>optional string last_name = 10;</code>
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string last_name = 10;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string last_name = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string last_name = 10;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 10;</code>
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000200);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 10;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        lastName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Person)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\010tutorial\"\273\001\n\006Person\022\014\n\004nam" +
      "e\030\001 \002(\t\022\027\n\017favorite_number\030\002 \001(\t\022\026\n\016favo" +
      "rite_color\030\003 \001(\t\022\013\n\003age\030\004 \001(\t\022\016\n\006class1\030" +
      "\005 \001(\t\022\016\n\006number\030\006 \001(\t\022\017\n\007address\030\007 \001(\t\022\r" +
      "\n\005phone\030\010 \001(\t\022\022\n\nfirst_name\030\t \001(\t\022\021\n\tlas" +
      "t_name\030\n \001(\tB\037\n\027com.example.protocolbufB" +
      "\004User"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Person_descriptor,
              new java.lang.String[] { "Name", "FavoriteNumber", "FavoriteColor", "Age", "Class1", "Number", "Address", "Phone", "FirstName", "LastName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
