/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.eastsoft.router.ipc.proto;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GatewayInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GatewayInfo\",\"namespace\":\"com.eastsoft.router.ipc.proto\",\"fields\":[{\"name\":\"gid\",\"type\":\"long\"},{\"name\":\"badBridgeIp\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long gid;
  @Deprecated public java.lang.String badBridgeIp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public GatewayInfo() {}

  /**
   * All-args constructor.
   */
  public GatewayInfo(java.lang.Long gid, java.lang.String badBridgeIp) {
    this.gid = gid;
    this.badBridgeIp = badBridgeIp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gid;
    case 1: return badBridgeIp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gid = (java.lang.Long)value$; break;
    case 1: badBridgeIp = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'gid' field.
   */
  public java.lang.Long getGid() {
    return gid;
  }

  /**
   * Sets the value of the 'gid' field.
   * @param value the value to set.
   */
  public void setGid(java.lang.Long value) {
    this.gid = value;
  }

  /**
   * Gets the value of the 'badBridgeIp' field.
   */
  public java.lang.String getBadBridgeIp() {
    return badBridgeIp;
  }

  /**
   * Sets the value of the 'badBridgeIp' field.
   * @param value the value to set.
   */
  public void setBadBridgeIp(java.lang.String value) {
    this.badBridgeIp = value;
  }

  /** Creates a new GatewayInfo RecordBuilder */
  public static com.eastsoft.router.ipc.proto.GatewayInfo.Builder newBuilder() {
    return new com.eastsoft.router.ipc.proto.GatewayInfo.Builder();
  }
  
  /** Creates a new GatewayInfo RecordBuilder by copying an existing Builder */
  public static com.eastsoft.router.ipc.proto.GatewayInfo.Builder newBuilder(com.eastsoft.router.ipc.proto.GatewayInfo.Builder other) {
    return new com.eastsoft.router.ipc.proto.GatewayInfo.Builder(other);
  }
  
  /** Creates a new GatewayInfo RecordBuilder by copying an existing GatewayInfo instance */
  public static com.eastsoft.router.ipc.proto.GatewayInfo.Builder newBuilder(com.eastsoft.router.ipc.proto.GatewayInfo other) {
    return new com.eastsoft.router.ipc.proto.GatewayInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for GatewayInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GatewayInfo>
    implements org.apache.avro.data.RecordBuilder<GatewayInfo> {

    private long gid;
    private java.lang.String badBridgeIp;

    /** Creates a new Builder */
    private Builder() {
      super(com.eastsoft.router.ipc.proto.GatewayInfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.eastsoft.router.ipc.proto.GatewayInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gid)) {
        this.gid = data().deepCopy(fields()[0].schema(), other.gid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.badBridgeIp)) {
        this.badBridgeIp = data().deepCopy(fields()[1].schema(), other.badBridgeIp);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing GatewayInfo instance */
    private Builder(com.eastsoft.router.ipc.proto.GatewayInfo other) {
            super(com.eastsoft.router.ipc.proto.GatewayInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.gid)) {
        this.gid = data().deepCopy(fields()[0].schema(), other.gid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.badBridgeIp)) {
        this.badBridgeIp = data().deepCopy(fields()[1].schema(), other.badBridgeIp);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'gid' field */
    public java.lang.Long getGid() {
      return gid;
    }
    
    /** Sets the value of the 'gid' field */
    public com.eastsoft.router.ipc.proto.GatewayInfo.Builder setGid(long value) {
      validate(fields()[0], value);
      this.gid = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'gid' field has been set */
    public boolean hasGid() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'gid' field */
    public com.eastsoft.router.ipc.proto.GatewayInfo.Builder clearGid() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'badBridgeIp' field */
    public java.lang.String getBadBridgeIp() {
      return badBridgeIp;
    }
    
    /** Sets the value of the 'badBridgeIp' field */
    public com.eastsoft.router.ipc.proto.GatewayInfo.Builder setBadBridgeIp(java.lang.String value) {
      validate(fields()[1], value);
      this.badBridgeIp = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'badBridgeIp' field has been set */
    public boolean hasBadBridgeIp() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'badBridgeIp' field */
    public com.eastsoft.router.ipc.proto.GatewayInfo.Builder clearBadBridgeIp() {
      badBridgeIp = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public GatewayInfo build() {
      try {
        GatewayInfo record = new GatewayInfo();
        record.gid = fieldSetFlags()[0] ? this.gid : (java.lang.Long) defaultValue(fields()[0]);
        record.badBridgeIp = fieldSetFlags()[1] ? this.badBridgeIp : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
