/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.eastsoft.router.ipc.proto;

@SuppressWarnings("all")
/** * An protocol define in Avro IDL */
@org.apache.avro.specific.AvroGenerated
public interface RouterProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RouterProtocol\",\"namespace\":\"com.eastsoft.router.ipc.proto\",\"doc\":\"* An protocol define in Avro IDL\",\"types\":[{\"type\":\"record\",\"name\":\"MobileInfo\",\"fields\":[{\"name\":\"gid\",\"type\":\"long\"},{\"name\":\"optionalMobileType\",\"type\":[\"null\",{\"type\":\"string\",\"java-class\":\"java.lang.String\"}]},{\"name\":\"optionalIMEI\",\"type\":[\"null\",{\"type\":\"string\",\"java-class\":\"java.lang.String\"}]},{\"name\":\"optionalTelNumber\",\"type\":[\"null\",{\"type\":\"string\",\"java-class\":\"java.lang.String\"}]}]},{\"type\":\"record\",\"name\":\"IpsAndToken\",\"fields\":[{\"name\":\"bridgeIp\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.String\"}},{\"name\":\"token\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.String\"}},{\"name\":\"routerList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"java-class\":\"java.lang.String\"}}}]},{\"type\":\"record\",\"name\":\"GatewayInfo\",\"fields\":[{\"name\":\"gid\",\"type\":\"long\"},{\"name\":\"badBridgeIp\",\"type\":{\"type\":\"string\",\"java-class\":\"java.lang.String\"}}]},{\"type\":\"error\",\"name\":\"ServiceException\",\"fields\":[{\"name\":\"errorCode\",\"type\":\"int\"},{\"name\":\"description\",\"type\":[\"null\",{\"type\":\"string\",\"java-class\":\"java.lang.String\"}]}]}],\"messages\":{\"requestMobileLogin\":{\"doc\":\"手机登陆请求\",\"request\":[{\"name\":\"mobileInfo\",\"type\":\"MobileInfo\"}],\"response\":\"IpsAndToken\",\"errors\":[\"ServiceException\"]},\"requestGatewayLogin\":{\"doc\":\"网关登陆请求\",\"request\":[{\"name\":\"gatewayInfo\",\"type\":\"GatewayInfo\"}],\"response\":\"IpsAndToken\",\"errors\":[\"ServiceException\"]}}}");
  /** 手机登陆请求 */
  com.eastsoft.router.ipc.proto.IpsAndToken requestMobileLogin(com.eastsoft.router.ipc.proto.MobileInfo mobileInfo) throws org.apache.avro.AvroRemoteException, com.eastsoft.router.ipc.proto.ServiceException;
  /** 网关登陆请求 */
  com.eastsoft.router.ipc.proto.IpsAndToken requestGatewayLogin(com.eastsoft.router.ipc.proto.GatewayInfo gatewayInfo) throws org.apache.avro.AvroRemoteException, com.eastsoft.router.ipc.proto.ServiceException;

  @SuppressWarnings("all")
  /** * An protocol define in Avro IDL */
  public interface Callback extends RouterProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.eastsoft.router.ipc.proto.RouterProtocol.PROTOCOL;
    /** 手机登陆请求 */
    void requestMobileLogin(com.eastsoft.router.ipc.proto.MobileInfo mobileInfo, org.apache.avro.ipc.Callback<com.eastsoft.router.ipc.proto.IpsAndToken> callback) throws java.io.IOException;
    /** 网关登陆请求 */
    void requestGatewayLogin(com.eastsoft.router.ipc.proto.GatewayInfo gatewayInfo, org.apache.avro.ipc.Callback<com.eastsoft.router.ipc.proto.IpsAndToken> callback) throws java.io.IOException;
  }
}