/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.eastsoft.river.router.proto.service1;

@SuppressWarnings("all")
/** * An protocol define in Avro IDL */
@org.apache.avro.specific.AvroGenerated
public interface Protocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Protocol\",\"namespace\":\"com.eastsoft.river.router.proto.service1\",\"doc\":\"* An protocol define in Avro IDL\",\"types\":[{\"type\":\"record\",\"name\":\"MobileInfo\",\"fields\":[{\"name\":\"gid\",\"type\":\"string\"},{\"name\":\"timeStamp\",\"type\":\"string\"},{\"name\":\"optionalIMEI\",\"type\":[\"null\",\"string\"]},{\"name\":\"optionalTelNumber\",\"type\":[\"null\",\"string\"]}]},{\"type\":\"record\",\"name\":\"IpsAndToken\",\"fields\":[{\"name\":\"bridgeIp\",\"type\":\"string\"},{\"name\":\"token\",\"type\":\"string\"},{\"name\":\"routerList\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]},{\"type\":\"record\",\"name\":\"GatewayInfo\",\"fields\":[{\"name\":\"gid\",\"type\":\"string\"},{\"name\":\"timeStamp\",\"type\":\"string\"}]},{\"type\":\"error\",\"name\":\"ServiceException\",\"fields\":[{\"name\":\"errorCode\",\"type\":\"int\"},{\"name\":\"description\",\"type\":[\"null\",\"string\"]}]}],\"messages\":{\"requestMobileLogin\":{\"request\":[{\"name\":\"mobileInfo\",\"type\":\"MobileInfo\"}],\"response\":\"IpsAndToken\",\"errors\":[\"ServiceException\"]},\"requestGatewayLogin\":{\"request\":[{\"name\":\"gatewayInfo\",\"type\":\"GatewayInfo\"}],\"response\":\"IpsAndToken\",\"errors\":[\"ServiceException\"]}}}");
  com.eastsoft.river.router.proto.service1.IpsAndToken requestMobileLogin(com.eastsoft.river.router.proto.service1.MobileInfo mobileInfo) throws org.apache.avro.AvroRemoteException, com.eastsoft.river.router.proto.service1.ServiceException;
  com.eastsoft.river.router.proto.service1.IpsAndToken requestGatewayLogin(com.eastsoft.river.router.proto.service1.GatewayInfo gatewayInfo) throws org.apache.avro.AvroRemoteException, com.eastsoft.river.router.proto.service1.ServiceException;

  @SuppressWarnings("all")
  /** * An protocol define in Avro IDL */
  public interface Callback extends Protocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.eastsoft.river.router.proto.service1.Protocol.PROTOCOL;
    void requestMobileLogin(com.eastsoft.river.router.proto.service1.MobileInfo mobileInfo, org.apache.avro.ipc.Callback<com.eastsoft.river.router.proto.service1.IpsAndToken> callback) throws java.io.IOException;
    void requestGatewayLogin(com.eastsoft.river.router.proto.service1.GatewayInfo gatewayInfo, org.apache.avro.ipc.Callback<com.eastsoft.river.router.proto.service1.IpsAndToken> callback) throws java.io.IOException;
  }
}