/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.cassandra.db.migration.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AddKeyspace extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AddKeyspace\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"ks\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence ks;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AddKeyspace() {}

  /**
   * All-args constructor.
   */
  public AddKeyspace(java.lang.CharSequence ks) {
    this.ks = ks;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ks;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ks = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ks' field.
   */
  public java.lang.CharSequence getKs() {
    return ks;
  }

  /**
   * Sets the value of the 'ks' field.
   * @param value the value to set.
   */
  public void setKs(java.lang.CharSequence value) {
    this.ks = value;
  }

  /** Creates a new AddKeyspace RecordBuilder */
  public static org.apache.cassandra.db.migration.avro.AddKeyspace.Builder newBuilder() {
    return new org.apache.cassandra.db.migration.avro.AddKeyspace.Builder();
  }
  
  /** Creates a new AddKeyspace RecordBuilder by copying an existing Builder */
  public static org.apache.cassandra.db.migration.avro.AddKeyspace.Builder newBuilder(org.apache.cassandra.db.migration.avro.AddKeyspace.Builder other) {
    return new org.apache.cassandra.db.migration.avro.AddKeyspace.Builder(other);
  }
  
  /** Creates a new AddKeyspace RecordBuilder by copying an existing AddKeyspace instance */
  public static org.apache.cassandra.db.migration.avro.AddKeyspace.Builder newBuilder(org.apache.cassandra.db.migration.avro.AddKeyspace other) {
    return new org.apache.cassandra.db.migration.avro.AddKeyspace.Builder(other);
  }
  
  /**
   * RecordBuilder for AddKeyspace instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AddKeyspace>
    implements org.apache.avro.data.RecordBuilder<AddKeyspace> {

    private java.lang.CharSequence ks;

    /** Creates a new Builder */
    private Builder() {
      super(org.apache.cassandra.db.migration.avro.AddKeyspace.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.apache.cassandra.db.migration.avro.AddKeyspace.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ks)) {
        this.ks = data().deepCopy(fields()[0].schema(), other.ks);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AddKeyspace instance */
    private Builder(org.apache.cassandra.db.migration.avro.AddKeyspace other) {
            super(org.apache.cassandra.db.migration.avro.AddKeyspace.SCHEMA$);
      if (isValidValue(fields()[0], other.ks)) {
        this.ks = data().deepCopy(fields()[0].schema(), other.ks);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'ks' field */
    public java.lang.CharSequence getKs() {
      return ks;
    }
    
    /** Sets the value of the 'ks' field */
    public org.apache.cassandra.db.migration.avro.AddKeyspace.Builder setKs(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ks = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'ks' field has been set */
    public boolean hasKs() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'ks' field */
    public org.apache.cassandra.db.migration.avro.AddKeyspace.Builder clearKs() {
      ks = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AddKeyspace build() {
      try {
        AddKeyspace record = new AddKeyspace();
        record.ks = fieldSetFlags()[0] ? this.ks : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
