/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.cassandra.db.migration.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RenameKeyspace extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RenameKeyspace\",\"namespace\":\"org.apache.cassandra.db.migration.avro\",\"fields\":[{\"name\":\"old_ksname\",\"type\":\"string\"},{\"name\":\"new_ksname\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence old_ksname;
  @Deprecated public java.lang.CharSequence new_ksname;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public RenameKeyspace() {}

  /**
   * All-args constructor.
   */
  public RenameKeyspace(java.lang.CharSequence old_ksname, java.lang.CharSequence new_ksname) {
    this.old_ksname = old_ksname;
    this.new_ksname = new_ksname;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return old_ksname;
    case 1: return new_ksname;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: old_ksname = (java.lang.CharSequence)value$; break;
    case 1: new_ksname = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'old_ksname' field.
   */
  public java.lang.CharSequence getOldKsname() {
    return old_ksname;
  }

  /**
   * Sets the value of the 'old_ksname' field.
   * @param value the value to set.
   */
  public void setOldKsname(java.lang.CharSequence value) {
    this.old_ksname = value;
  }

  /**
   * Gets the value of the 'new_ksname' field.
   */
  public java.lang.CharSequence getNewKsname() {
    return new_ksname;
  }

  /**
   * Sets the value of the 'new_ksname' field.
   * @param value the value to set.
   */
  public void setNewKsname(java.lang.CharSequence value) {
    this.new_ksname = value;
  }

  /** Creates a new RenameKeyspace RecordBuilder */
  public static org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder newBuilder() {
    return new org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder();
  }
  
  /** Creates a new RenameKeyspace RecordBuilder by copying an existing Builder */
  public static org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder newBuilder(org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder other) {
    return new org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder(other);
  }
  
  /** Creates a new RenameKeyspace RecordBuilder by copying an existing RenameKeyspace instance */
  public static org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder newBuilder(org.apache.cassandra.db.migration.avro.RenameKeyspace other) {
    return new org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder(other);
  }
  
  /**
   * RecordBuilder for RenameKeyspace instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RenameKeyspace>
    implements org.apache.avro.data.RecordBuilder<RenameKeyspace> {

    private java.lang.CharSequence old_ksname;
    private java.lang.CharSequence new_ksname;

    /** Creates a new Builder */
    private Builder() {
      super(org.apache.cassandra.db.migration.avro.RenameKeyspace.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.old_ksname)) {
        this.old_ksname = data().deepCopy(fields()[0].schema(), other.old_ksname);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.new_ksname)) {
        this.new_ksname = data().deepCopy(fields()[1].schema(), other.new_ksname);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing RenameKeyspace instance */
    private Builder(org.apache.cassandra.db.migration.avro.RenameKeyspace other) {
            super(org.apache.cassandra.db.migration.avro.RenameKeyspace.SCHEMA$);
      if (isValidValue(fields()[0], other.old_ksname)) {
        this.old_ksname = data().deepCopy(fields()[0].schema(), other.old_ksname);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.new_ksname)) {
        this.new_ksname = data().deepCopy(fields()[1].schema(), other.new_ksname);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'old_ksname' field */
    public java.lang.CharSequence getOldKsname() {
      return old_ksname;
    }
    
    /** Sets the value of the 'old_ksname' field */
    public org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder setOldKsname(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.old_ksname = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'old_ksname' field has been set */
    public boolean hasOldKsname() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'old_ksname' field */
    public org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder clearOldKsname() {
      old_ksname = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'new_ksname' field */
    public java.lang.CharSequence getNewKsname() {
      return new_ksname;
    }
    
    /** Sets the value of the 'new_ksname' field */
    public org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder setNewKsname(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.new_ksname = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'new_ksname' field has been set */
    public boolean hasNewKsname() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'new_ksname' field */
    public org.apache.cassandra.db.migration.avro.RenameKeyspace.Builder clearNewKsname() {
      new_ksname = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public RenameKeyspace build() {
      try {
        RenameKeyspace record = new RenameKeyspace();
        record.old_ksname = fieldSetFlags()[0] ? this.old_ksname : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.new_ksname = fieldSetFlags()[1] ? this.new_ksname : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
